# Generated by Django 3.2.8 on 2021-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='almacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('cant_almacenamiento', models.IntegerField()),
                ('tipo_unidad', models.CharField(max_length=10)),
                ('forma_almacen', models.CharField(max_length=5)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pc_armadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=30)),
                ('t_video', models.CharField(default='No tiene', max_length=50)),
                ('rom', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='procesadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('cant_unidades_data', models.IntegerField()),
                ('tipo_unidad', models.CharField(default='GB', max_length=10)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Targetas_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
